---
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - rustup component add rustfmt
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo fmt -- --check
